import type { TroubleshootingWorkflow } from "@/lib/toolkit/guided/types";

const sharedActions = {
  closeApps: {
    id: "close-unused-apps",
    title: "Close unused applications",
    why: "Idle apps often hold memory and background CPU that can make the system feel slow.",
    caution: "Save work before closing apps you still need.",
    classification: "try-now" as const,
    simulated: true,
    remediation: "close-unused-process" as const,
    relatedModule: "memory" as const,
  },
  reviewStartup: {
    id: "review-startup",
    title: "Review startup programs",
    why: "Fewer launchers at sign-in can improve early-session responsiveness.",
    classification: "monitor" as const,
    simulated: true,
    remediation: "disable-startup-item" as const,
    relatedModule: "system" as const,
  },
  restartAfterSave: {
    id: "restart-after-save",
    title: "Restart after saving work",
    why: "A clean boot clears long-running process drift when issues persist.",
    caution: "Save open documents first. This demo does not restart your computer.",
    classification: "requires-restart" as const,
    simulated: false,
    relatedModule: "system" as const,
  },
  support: {
    id: "professional-support",
    title: "Consider professional support",
    why: "Persistent heat, storage failure signs, or repeated freezes may need hands-on help.",
    caution: "Avoid hazardous disassembly guidance from unverified sources.",
    classification: "professional-support" as const,
    simulated: false,
  },
};

export const WORKFLOWS: TroubleshootingWorkflow[] = [
  {
    id: "slow-computer",
    title: "Computer Running Slowly",
    shortDescription: "Walk through CPU, memory, processes, storage, and startup checks.",
    relatedModules: ["system", "memory"],
    recommendedScenario: "heavy-memory",
    scenarioRationale: "Heavy Memory Usage makes memory pressure and process load easy to observe.",
    findings: {
      "mem-high": {
        category: "Memory",
        status: "high",
        explanation: "High memory pressure may be contributing to slow performance.",
        relatedModule: "memory",
        confidence: "The current simulation suggests memory is a likely contributor—not the only possible cause.",
        nextAction: "Inspect memory-heavy processes and close unused applications.",
      },
      "cpu-high": {
        category: "CPU",
        status: "attention",
        explanation: "Elevated CPU usage may contribute to temporary sluggishness.",
        relatedModule: "system",
        confidence: "This may contribute to the reported slowdown.",
        nextAction: "Identify high-CPU processes and distinguish spikes from sustained load.",
      },
      "disk-low": {
        category: "Storage",
        status: "attention",
        explanation: "Limited free space can affect caching, updates, and overall responsiveness.",
        relatedModule: "system",
        confidence: "Low free space may contribute when other resources are also busy.",
        nextAction: "Review temporary files and large downloads.",
      },
      "resources-ok": {
        category: "Overall",
        status: "normal",
        explanation: "Primary resource gauges look ordinary; the slowdown may be app-specific or external.",
        relatedModule: "overview",
        confidence: "Local gauges alone do not prove a complete cause.",
        nextAction: "Continue with process and startup checks for remaining clues.",
      },
    },
    actions: {
      closeApps: sharedActions.closeApps,
      reviewStartup: sharedActions.reviewStartup,
      clearTemp: {
        id: "clear-temp",
        title: "Simulate clearing temporary files",
        why: "Temp clutter can reclaim useful free space on the system volume.",
        caution: "Simulated only — no real files are deleted.",
        classification: "try-now",
        simulated: true,
        remediation: "clear-temp-files",
        relatedModule: "system",
      },
      restartAfterSave: sharedActions.restartAfterSave,
    },
    steps: [
      {
        type: "introduction",
        id: "intro",
        title: "Start: Computer Running Slowly",
        body: "We will review CPU, memory, processes, storage, and startup impact one check at a time. No single reading proves the full cause.",
        next: "check-cpu",
      },
      {
        type: "diagnostic-check",
        id: "check-cpu",
        title: "Review CPU usage",
        checkId: "cpu",
        skippable: true,
        branches: [
          { when: { metric: "cpu", op: "gte", value: 45 }, next: "check-memory", findingId: "cpu-high" },
        ],
        defaultNext: "check-memory",
      },
      {
        type: "diagnostic-check",
        id: "check-memory",
        title: "Review memory usage",
        checkId: "memory",
        skippable: true,
        branches: [
          { when: { metric: "memory", op: "gte", value: 80 }, next: "link-memory", findingId: "mem-high" },
          { when: { metric: "memory", op: "lt", value: 80 }, next: "check-processes" },
        ],
        defaultNext: "check-processes",
      },
      {
        type: "module-link",
        id: "link-memory",
        title: "Inspect memory diagnostics",
        module: "memory",
        href: "/toolkit/memory",
        linkLabel: "Open Memory Diagnostics",
        body: "Memory pressure looks elevated. Review the live process list, then return here to continue.",
        next: "check-processes",
      },
      {
        type: "diagnostic-check",
        id: "check-processes",
        title: "Inspect active processes",
        checkId: "processes",
        skippable: true,
        branches: [],
        defaultNext: "check-storage",
      },
      {
        type: "diagnostic-check",
        id: "check-storage",
        title: "Check free disk space",
        checkId: "storage",
        skippable: true,
        branches: [
          { when: { metric: "diskUsedPercent", op: "gte", value: 85 }, next: "check-startup", findingId: "disk-low" },
        ],
        defaultNext: "check-startup",
      },
      {
        type: "diagnostic-check",
        id: "check-startup",
        title: "Review startup-program impact",
        checkId: "startup",
        skippable: true,
        branches: [],
        defaultNext: "ask-persist",
      },
      {
        type: "question",
        id: "ask-persist",
        title: "How often does the slowdown appear?",
        prompt: "In this simulation, how would you describe the issue pattern?",
        options: [
          { id: "always", label: "It feels slow most of the time", next: "simulate-close" },
          { id: "after-boot", label: "Mostly right after startup", next: "simulate-close" },
          { id: "one-app", label: "Mostly inside one application", next: "simulate-close" },
        ],
      },
      {
        type: "action",
        id: "simulate-close",
        title: "Try a safe simulated fix",
        body: "You can simulate closing an unused process to see how memory readings respond. This never touches real processes.",
        remediation: "close-unused-process",
        actionLabel: "Simulate closing an unused process",
        next: "recs",
        skippable: true,
      },
      {
        type: "recommendation",
        id: "recs",
        title: "Recommended actions",
        body: "These actions are framed as safe next steps for the simulation. Prefer saving work before any restart guidance.",
        actionIds: ["closeApps", "reviewStartup", "clearTemp", "restartAfterSave"],
        next: "summary",
      },
      {
        type: "summary",
        id: "summary",
        title: "Troubleshooting summary",
        conclusionTemplate:
          "The simulation suggests that {findings} are the most relevant signals for the reported slowdown under the {profile} profile. Closing unused applications can improve simulated memory load, while reviewing startup programs remains a reasonable next step. This does not mean the issue is permanently solved.",
      },
    ],
  },
  {
    id: "slow-internet",
    title: "Internet Connection Feels Slow",
    shortDescription: "Check link state, latency, packet loss, DNS, and wired vs wireless guidance.",
    relatedModules: ["network"],
    recommendedScenario: "network-instability",
    scenarioRationale: "Network Instability elevates latency, packet loss, and DNS delay for a clear walkthrough.",
    findings: {
      "latency-high": {
        category: "Latency",
        status: "attention",
        explanation: "Elevated latency may contribute to sluggish browsing and calls.",
        relatedModule: "network",
        confidence: "The current simulation suggests latency is a contributor.",
        nextAction: "Compare wired vs wireless and consider a gateway restart simulation.",
      },
      "loss-high": {
        category: "Packet loss",
        status: "high",
        explanation: "Packet loss can cause retries and uneven responsiveness.",
        relatedModule: "network",
        confidence: "This may contribute to the reported slow connection.",
        nextAction: "Reduce wireless interference and retest after a simulated router restart.",
      },
      "dns-slow": {
        category: "DNS",
        status: "attention",
        explanation: "Slow DNS responses can make sites feel delayed even when throughput looks fine.",
        relatedModule: "network",
        confidence: "DNS delay appears more prominent than packet loss in this reading.",
        nextAction: "Retest after reconnecting and note whether all sites are affected.",
      },
      "network-ok": {
        category: "Local network",
        status: "normal",
        explanation: "Local network gauges look ordinary; the issue may be external or service-specific.",
        relatedModule: "network",
        confidence: "Healthy local metrics do not rule out an upstream or website issue.",
        nextAction: "Check whether one service or all services feel slow.",
      },
    },
    actions: {
      restartRouter: {
        id: "restart-router",
        title: "Simulate restarting the modem/router",
        why: "A gateway reboot often clears transient congestion in demos and real homes alike.",
        caution: "Simulated only — no real router is contacted.",
        classification: "try-now",
        simulated: true,
        remediation: "restart-router",
        relatedModule: "network",
      },
      wired: {
        id: "try-wired",
        title: "Test a wired connection",
        why: "Ethernet usually reduces wireless interference while troubleshooting.",
        classification: "monitor",
        simulated: false,
        relatedModule: "network",
      },
      moveCloser: {
        id: "move-closer",
        title: "Move closer to the access point",
        why: "Stronger signal can reduce retries on Wi-Fi.",
        classification: "try-now",
        simulated: false,
        relatedModule: "network",
      },
      pauseDownloads: {
        id: "pause-downloads",
        title: "Pause large downloads",
        why: "Saturated uplinks can make interactive traffic feel slow.",
        classification: "try-now",
        simulated: false,
      },
      isp: {
        id: "contact-isp",
        title: "Contact the service provider if multiple devices are affected",
        why: "When several devices share the same symptom, the issue may be upstream.",
        caution: "This demo never contacted a real ISP.",
        classification: "professional-support",
        simulated: false,
      },
      reconnect: {
        id: "reconnect",
        title: "Simulate reconnecting to the network",
        why: "A fresh association can clear stale wireless state in the simulation.",
        caution: "Simulated only.",
        classification: "try-now",
        simulated: true,
        remediation: "reconnect-network",
        relatedModule: "network",
      },
    },
    steps: [
      {
        type: "introduction",
        id: "intro",
        title: "Start: Internet Feels Slow",
        body: "We will check connection state, latency, packet loss, and DNS. Results are simulated and do not contact your ISP or router.",
        next: "check-connection",
      },
      {
        type: "diagnostic-check",
        id: "check-connection",
        title: "Check connection state",
        checkId: "connection",
        branches: [],
        defaultNext: "check-latency",
      },
      {
        type: "diagnostic-check",
        id: "check-latency",
        title: "Review latency",
        checkId: "latency",
        skippable: true,
        branches: [
          { when: { metric: "latency", op: "gte", value: 60 }, next: "check-loss", findingId: "latency-high" },
        ],
        defaultNext: "check-loss",
      },
      {
        type: "diagnostic-check",
        id: "check-loss",
        title: "Review packet loss",
        checkId: "packetLoss",
        skippable: true,
        branches: [
          { when: { metric: "packetLoss", op: "gte", value: 1 }, next: "check-dns", findingId: "loss-high" },
          {
            when: {
              all: [
                { metric: "packetLoss", op: "lt", value: 1 },
                { metric: "dnsMs", op: "gte", value: 50 },
              ],
            },
            next: "check-dns",
            findingId: "dns-slow",
          },
          {
            when: {
              all: [
                { metric: "packetLoss", op: "lt", value: 1 },
                { metric: "latency", op: "lt", value: 40 },
                { metric: "dnsMs", op: "lt", value: 40 },
              ],
            },
            next: "check-dns",
            findingId: "network-ok",
          },
        ],
        defaultNext: "check-dns",
      },
      {
        type: "diagnostic-check",
        id: "check-dns",
        title: "Review DNS response time",
        checkId: "dns",
        skippable: true,
        branches: [
          {
            when: {
              all: [
                { metric: "packetLoss", op: "lt", value: 1 },
                { metric: "dnsMs", op: "gte", value: 50 },
              ],
            },
            next: "link-network",
            findingId: "dns-slow",
          },
        ],
        defaultNext: "link-network",
      },
      {
        type: "module-link",
        id: "link-network",
        title: "Open network diagnostics",
        module: "network",
        href: "/toolkit/network",
        linkLabel: "Open Network Diagnostics",
        body: "Review adapters, quality history, and DNS providers, then return to finish this guide.",
        next: "ask-scope",
      },
      {
        type: "question",
        id: "ask-scope",
        title: "Is the slowdown local or broad?",
        prompt: "Which pattern best matches what you want to explore?",
        options: [
          { id: "wifi-only", label: "Mostly on Wi-Fi", next: "wired-guidance" },
          { id: "all-devices", label: "Multiple devices feel slow", next: "action-router" },
          { id: "one-site", label: "One website or service", next: "recs" },
        ],
      },
      {
        type: "finding",
        id: "wired-guidance",
        title: "Wired versus wireless",
        body: "A reasonable next check is testing Ethernet if available. Wireless interference can amplify jitter even when the ISP path is fine.",
        next: "action-router",
      },
      {
        type: "action",
        id: "action-router",
        title: "Simulate router restart",
        body: "Optionally simulate a modem/router restart to observe latency and packet-loss changes.",
        remediation: "restart-router",
        actionLabel: "Simulate restarting the router",
        next: "recs",
        skippable: true,
      },
      {
        type: "recommendation",
        id: "recs",
        title: "Safe next steps",
        body: "Use these actions as a checklist. None of them change your real network equipment from this demo.",
        actionIds: ["restartRouter", "wired", "moveCloser", "pauseDownloads", "reconnect", "isp"],
        next: "summary",
      },
      {
        type: "summary",
        id: "summary",
        title: "Network troubleshooting summary",
        conclusionTemplate:
          "Under the {profile} profile, the simulation highlights {findings}. Local checks never contacted a real ISP or router. If multiple devices remain affected after basic steps, contacting the provider is a reasonable escalation—not a claim that this demo diagnosed your service.",
      },
    ],
  },
  {
    id: "storage-full",
    title: "Storage Is Almost Full",
    shortDescription: "Review capacity, categories, temp files, and simulated cleanup.",
    relatedModules: ["system"],
    recommendedScenario: "low-disk",
    scenarioRationale: "Low Disk Space puts the system volume near capacity so cleanup guidance is meaningful.",
    findings: {
      "disk-critical": {
        category: "Capacity",
        status: "high",
        explanation: "The system volume is nearly full, leaving little room for updates and caches.",
        relatedModule: "system",
        confidence: "The current simulation strongly suggests free-space pressure.",
        nextAction: "Simulate temporary-file cleanup and review large downloads.",
      },
      "disk-ok": {
        category: "Capacity",
        status: "normal",
        explanation: "Free space looks adequate; fullness may be limited to a secondary volume or perception.",
        relatedModule: "system",
        confidence: "Primary-volume readings do not show critical pressure.",
        nextAction: "Still review categories if a specific folder feels crowded.",
      },
    },
    actions: {
      clearTemp: {
        id: "clear-temp",
        title: "Simulate clearing temporary files",
        why: "Temp and installer leftovers often reclaim several gigabytes safely in demos.",
        caution: "Simulated only — no real files are deleted.",
        classification: "try-now",
        simulated: true,
        remediation: "clear-temp-files",
        relatedModule: "system",
      },
      moveLarge: {
        id: "move-large",
        title: "Move large files to secondary storage",
        why: "Relocating archives and media restores headroom without deleting projects.",
        classification: "monitor",
        simulated: false,
        relatedModule: "system",
      },
      emptyBin: {
        id: "empty-bin",
        title: "Empty recycle bin (guidance only)",
        why: "Deleted items may still occupy space until the bin is emptied.",
        caution: "This demo does not empty a real recycle bin.",
        classification: "try-now",
        simulated: false,
      },
    },
    steps: [
      {
        type: "introduction",
        id: "intro",
        title: "Start: Storage Almost Full",
        body: "We will review capacity, categories, and cleanup options. Cleanup actions in this guide are simulated and never delete real files.",
        next: "check-storage",
      },
      {
        type: "diagnostic-check",
        id: "check-storage",
        title: "Review capacity",
        checkId: "storage",
        branches: [
          { when: { metric: "diskUsedPercent", op: "gte", value: 85 }, next: "categories", findingId: "disk-critical" },
          { when: { metric: "diskUsedPercent", op: "lt", value: 85 }, next: "categories", findingId: "disk-ok" },
        ],
        defaultNext: "categories",
      },
      {
        type: "finding",
        id: "categories",
        title: "Simulated storage categories",
        body: "Typical pressure comes from applications, media, downloads, and temporary files. Aim to keep roughly 15% free on the system volume when possible.",
        next: "link-storage",
      },
      {
        type: "module-link",
        id: "link-storage",
        title: "Review storage in SystemScope",
        module: "system",
        href: "/toolkit/system#storage",
        linkLabel: "Review Storage",
        body: "Open the storage panel for drive-level capacity bars, then return here.",
        next: "simulate-cleanup",
      },
      {
        type: "action",
        id: "simulate-cleanup",
        title: "Simulate Cleanup",
        body: "Run a simulated temporary-file cleanup to estimate recoverable space. This updates demo storage values only.",
        remediation: "clear-temp-files",
        actionLabel: "Simulate Cleanup",
        next: "recs",
        skippable: true,
      },
      {
        type: "recommendation",
        id: "recs",
        title: "Cleanup recommendations",
        body: "Combine simulated cleanup with practical organization habits. Nothing here accesses real files.",
        actionIds: ["clearTemp", "moveLarge", "emptyBin"],
        next: "summary",
      },
      {
        type: "summary",
        id: "summary",
        title: "Storage summary",
        conclusionTemplate:
          "With {profile}, used capacity is about {disk}. Findings: {findings}. Simulated cleanup can show estimated improvement, but it does not delete real files or permanently solve storage pressure.",
      },
    ],
  },
  {
    id: "apps-freezing",
    title: "Applications Keep Freezing",
    shortDescription: "Inspect memory, CPU, unresponsive processes, and recovery options.",
    relatedModules: ["memory", "system"],
    recommendedScenario: "heavy-memory",
    scenarioRationale: "Memory Pressure makes freeze-like contention easier to demonstrate.",
    findings: {
      "freeze-memory": {
        category: "Memory pressure",
        status: "high",
        explanation: "Memory saturation may contribute to applications becoming briefly unresponsive.",
        relatedModule: "memory",
        confidence: "This may contribute to freezes, especially in memory-heavy apps.",
        nextAction: "Wait briefly, save work if possible, then close and reopen the app.",
      },
      "freeze-cpu": {
        category: "CPU saturation",
        status: "attention",
        explanation: "Sustained CPU load can make UI threads feel frozen.",
        relatedModule: "system",
        confidence: "CPU pressure is a plausible contributor in this simulation.",
        nextAction: "Identify busy processes before force-closing anything.",
      },
      "freeze-disk": {
        category: "Storage",
        status: "monitor",
        explanation: "Low free space can worsen hitching when apps write caches or swap.",
        relatedModule: "system",
        confidence: "Storage is a secondary factor unless capacity is critically low.",
        nextAction: "Confirm free space after reviewing memory and CPU.",
      },
    },
    actions: {
      wait: {
        id: "wait-busy",
        title: "Wait briefly for a busy process",
        why: "Temporary spikes often clear without losing work.",
        classification: "monitor",
        simulated: false,
      },
      saveWork: {
        id: "save-work",
        title: "Save work when possible",
        why: "Preserving documents reduces risk if an app must be closed.",
        caution: "Avoid unsafe force-closing while unsaved work is open.",
        classification: "try-now",
        simulated: false,
      },
      reopen: {
        id: "reopen-app",
        title: "Close and reopen the application",
        why: "A clean app launch clears many stuck UI states.",
        caution: "Save first when you can.",
        classification: "try-now",
        simulated: false,
      },
      closeProcess: sharedActions.closeApps,
      updates: {
        id: "check-updates",
        title: "Review available updates",
        why: "Vendors often ship hang fixes in routine updates.",
        classification: "monitor",
        simulated: false,
      },
      restartAfterSave: sharedActions.restartAfterSave,
    },
    steps: [
      {
        type: "introduction",
        id: "intro",
        title: "Start: Apps Keep Freezing",
        body: "We will check memory pressure, CPU load, processes, and storage. Force-closing without saving can lose work—prefer safe recovery steps.",
        next: "check-memory",
      },
      {
        type: "diagnostic-check",
        id: "check-memory",
        title: "Review memory pressure",
        checkId: "memory",
        branches: [
          { when: { metric: "memory", op: "gte", value: 80 }, next: "check-cpu", findingId: "freeze-memory" },
        ],
        defaultNext: "check-cpu",
      },
      {
        type: "diagnostic-check",
        id: "check-cpu",
        title: "Review CPU saturation",
        checkId: "cpu",
        branches: [
          { when: { metric: "cpu", op: "gte", value: 55 }, next: "check-processes", findingId: "freeze-cpu" },
        ],
        defaultNext: "check-processes",
      },
      {
        type: "diagnostic-check",
        id: "check-processes",
        title: "Identify busy processes",
        checkId: "processes",
        branches: [],
        defaultNext: "link-memory",
      },
      {
        type: "module-link",
        id: "link-memory",
        title: "Inspect processes",
        module: "memory",
        href: "/toolkit/memory",
        linkLabel: "Inspect Processes",
        body: "Review which simulated processes are heavy, then return. Do not force-close real apps with unsaved work.",
        next: "check-storage",
      },
      {
        type: "diagnostic-check",
        id: "check-storage",
        title: "Check available storage",
        checkId: "storage",
        skippable: true,
        branches: [
          { when: { metric: "diskUsedPercent", op: "gte", value: 85 }, next: "recs", findingId: "freeze-disk" },
        ],
        defaultNext: "recs",
      },
      {
        type: "recommendation",
        id: "recs",
        title: "Recovery recommendations",
        body: "Start with waiting and saving work. Simulated process closes demonstrate memory relief without touching real apps.",
        actionIds: ["wait", "saveWork", "reopen", "closeProcess", "updates", "restartAfterSave"],
        next: "summary",
      },
      {
        type: "summary",
        id: "summary",
        title: "Freeze troubleshooting summary",
        conclusionTemplate:
          "The simulation points to {findings} under {profile}. Prefer saving work and reopening apps before any restart. Simulated actions never force-close real software.",
      },
    ],
  },
  {
    id: "running-hot",
    title: "Computer Is Running Hot",
    shortDescription: "Review simulated thermals, sustained CPU, and safe cooling guidance.",
    relatedModules: ["system"],
    recommendedScenario: "aging",
    scenarioRationale: "Aging Workstation models warmer thermals and sustained load characteristics.",
    findings: {
      "temp-high": {
        category: "Thermals",
        status: "high",
        explanation: "Simulated CPU temperature is elevated for sustained interactive work.",
        relatedModule: "system",
        confidence: "Heat appears meaningful in this profile, especially with sustained CPU.",
        nextAction: "Reduce heavy workloads and ensure ventilation on a hard surface.",
      },
      "temp-ok": {
        category: "Thermals",
        status: "normal",
        explanation: "Temperature looks ordinary; brief fan spin-ups can still feel warm to the touch.",
        relatedModule: "system",
        confidence: "Short spikes are less concerning than sustained heat.",
        nextAction: "Monitor whether warmth tracks with heavy apps.",
      },
      "sustained-cpu": {
        category: "Workload",
        status: "attention",
        explanation: "Sustained CPU usage can keep package temperatures elevated.",
        relatedModule: "system",
        confidence: "Workload is a likely contributor when thermals stay high.",
        nextAction: "Pause nonessential heavy tasks and reassess.",
      },
    },
    actions: {
      hardSurface: {
        id: "hard-surface",
        title: "Place the computer on a hard, ventilated surface",
        why: "Soft surfaces block intake vents and trap heat.",
        classification: "try-now",
        simulated: false,
      },
      clearVents: {
        id: "clear-vents",
        title: "Clear external vents carefully",
        why: "Dust at intakes raises sustained temperatures.",
        caution: "Do not disassemble internal hardware from this guide.",
        classification: "try-now",
        simulated: false,
      },
      reduceLoad: {
        id: "reduce-load",
        title: "Reduce sustained heavy workloads",
        why: "Lower sustained CPU often lowers package temperature quickly.",
        classification: "try-now",
        simulated: true,
        remediation: "close-unused-process",
      },
      inspectCooling: {
        id: "inspect-cooling",
        title: "Inspect cooling hardware if temperatures remain high",
        why: "Persistent heat after workload reduction may indicate airflow or cooler issues.",
        caution: "Seek qualified repair help rather than hazardous disassembly.",
        classification: "professional-support",
        simulated: false,
      },
      support: sharedActions.support,
    },
    steps: [
      {
        type: "introduction",
        id: "intro",
        title: "Start: Running Hot",
        body: "We will review simulated temperature, CPU load, and cooling status. This guide never instructs hazardous hardware disassembly.",
        next: "check-temp",
      },
      {
        type: "diagnostic-check",
        id: "check-temp",
        title: "Review simulated CPU temperature",
        checkId: "temperature",
        branches: [
          { when: { metric: "cpuTempC", op: "gte", value: 75 }, next: "check-cpu", findingId: "temp-high" },
          { when: { metric: "cpuTempC", op: "lt", value: 75 }, next: "check-cpu", findingId: "temp-ok" },
        ],
        defaultNext: "check-cpu",
      },
      {
        type: "diagnostic-check",
        id: "check-cpu",
        title: "Review sustained CPU usage",
        checkId: "cpu",
        branches: [
          { when: { metric: "cpu", op: "gte", value: 40 }, next: "ask-duration", findingId: "sustained-cpu" },
        ],
        defaultNext: "ask-duration",
      },
      {
        type: "question",
        id: "ask-duration",
        title: "Spike or sustained heat?",
        prompt: "Which pattern are you exploring?",
        options: [
          { id: "brief", label: "Brief warmth during heavy tasks", next: "recs" },
          { id: "sustained", label: "Stays hot even after tasks finish", next: "recs" },
        ],
      },
      {
        type: "recommendation",
        id: "recs",
        title: "Safe cooling recommendations",
        body: "Focus on ventilation and workload first. Internal repairs belong with qualified help.",
        actionIds: ["hardSurface", "clearVents", "reduceLoad", "inspectCooling", "support"],
        next: "summary",
      },
      {
        type: "summary",
        id: "summary",
        title: "Thermal summary",
        conclusionTemplate:
          "Under {profile}, findings include {findings}. Short spikes differ from sustained heat. This demo does not read real sensors and does not approve internal disassembly.",
      },
    ],
  },
  {
    id: "slow-startup",
    title: "Startup Takes Too Long",
    shortDescription: "Estimate startup time, review launchers, storage, and aging factors.",
    relatedModules: ["system", "memory"],
    recommendedScenario: "aging",
    scenarioRationale: "Aging Workstation emphasizes longer startup estimates and accumulated launchers.",
    findings: {
      "startup-slow": {
        category: "Startup",
        status: "attention",
        explanation: "Estimated startup time and enabled launchers suggest login backlog.",
        relatedModule: "system",
        confidence: "Startup items are a likely contributor in this simulation.",
        nextAction: "Simulate disabling a nonessential startup entry.",
      },
      "startup-storage": {
        category: "Storage",
        status: "monitor",
        explanation: "Limited free space can lengthen boot and login services.",
        relatedModule: "system",
        confidence: "Storage may contribute alongside startup backlog.",
        nextAction: "Combine launcher trimming with free-space recovery.",
      },
    },
    actions: {
      disableStartup: {
        id: "disable-startup",
        title: "Simulate disabling a nonessential startup item",
        why: "Fewer high-impact launchers shorten the first minutes after login.",
        caution: "Simulated only — real startup apps are unchanged.",
        classification: "try-now",
        simulated: true,
        remediation: "disable-startup-item",
        relatedModule: "system",
      },
      reviewStartup: sharedActions.reviewStartup,
      clearTemp: {
        id: "clear-temp",
        title: "Simulate clearing temporary files",
        why: "More free space can help update and service startup paths.",
        caution: "Simulated only.",
        classification: "try-now",
        simulated: true,
        remediation: "clear-temp-files",
      },
      restartAfterSave: sharedActions.restartAfterSave,
    },
    steps: [
      {
        type: "introduction",
        id: "intro",
        title: "Start: Slow Startup",
        body: "We will review startup estimate, launchers, storage, and aging factors. Disabling startup items here is simulated.",
        next: "check-startup",
      },
      {
        type: "diagnostic-check",
        id: "check-startup",
        title: "Review simulated startup estimate",
        checkId: "startup",
        branches: [
          { when: { metric: "startupSeconds", op: "gte", value: 55 }, next: "list-startup", findingId: "startup-slow" },
        ],
        defaultNext: "list-startup",
      },
      {
        type: "finding",
        id: "list-startup",
        title: "High-impact startup items",
        body: "Cloud sync, chat launchers, and updaters often dominate login time. Prefer disabling nonessential helpers first.",
        next: "check-storage",
      },
      {
        type: "diagnostic-check",
        id: "check-storage",
        title: "Review storage health and free space",
        checkId: "storage",
        skippable: true,
        branches: [
          { when: { metric: "diskUsedPercent", op: "gte", value: 80 }, next: "simulate-disable", findingId: "startup-storage" },
        ],
        defaultNext: "simulate-disable",
      },
      {
        type: "action",
        id: "simulate-disable",
        title: "Simulate disabling a startup item",
        body: "Disable a nonessential simulated launcher and observe lighter early-session load.",
        remediation: "disable-startup-item",
        actionLabel: "Simulate disabling a startup item",
        next: "recs",
        skippable: true,
      },
      {
        type: "recommendation",
        id: "recs",
        title: "Startup recommendations",
        body: "Trim launchers gradually so you can reverse course if something is needed daily.",
        actionIds: ["disableStartup", "reviewStartup", "clearTemp", "restartAfterSave"],
        next: "summary",
      },
      {
        type: "summary",
        id: "summary",
        title: "Startup summary",
        conclusionTemplate:
          "For {profile}, the guide highlights {findings}. Simulated launcher changes affect demo metrics only and do not modify your real startup configuration.",
      },
    ],
  },
];

export const WORKFLOW_BY_ID = Object.fromEntries(WORKFLOWS.map((item) => [item.id, item]));

export function listWorkflows() {
  return WORKFLOWS;
}

export function getWorkflow(id: string) {
  return WORKFLOW_BY_ID[id] ?? null;
}
